#配置端口号
server:
  port: 7071

#配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/k10_easybuy?useSSL=false
    username: root
    password: 123456789
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  #redis配置
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    database: 0
    host: 127.0.0.1
    prot: 6379
    timeout: 3000ms
  profiles:
    active: dev
  application:
    name: eb-web-banner-provider

#配置xml形式的mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo
#将服务注册到注册中心中去
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10010/eureka
