server:
  port: 9093

#配置数据库连接信息
spring:
  application:
    name: eb-web-seckill-consumer
#配置rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql///k10_easybuy
    username: root
    password: 123456789

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml