#配置端口号
server:
  port: 8080

#配置服务名
spring:
  application:
    name: eb_gateway

#将网关注册到注册中心中去
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10010/eureka

#配置子服务访问路径
zuul:
  routes:
    eb_admin: /admin/**
    eb_web: /web/**

  client:
    registerWithEureka: true
    fetchRegistry: true


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000